### ISSUE TITLE
Loading certain vim plugins

### ISSUE THREAD

**Issue by awesomefireduck** [sunaku/.vim#6]
I have a neovim setup which uses your amazing modular vim setup (master branch),
but I have trouble loading some plugins, and I thought that maybe you could help.  
There are several plugins I succesfully used for a while (several colourschemes, tpope/fugitive, jonstoler/werewolf, mhinz/vim-startify, to name a few).  
But I recently wanted to add the NERDcommenter plugin, and while it sucessfully inserts (with `./insert scrooloose/nerdcommenter completion`), It does not load.
running nvim with -V gets me:
```
[...]
line 20: sourcing "/home/$USER/.nvim/bundle/completion/nerdcommenter/./plugin/NERD_commenter.vim"
finished sourcing /home/$USER/.nvim/bundle/completion/nerdcommenter/./plugin/NERD_commenter.vim
[...]
```
I tested this with vim-nox 7.4.488 and neovim 0.0.0-alpha+201506250128 on ubuntu 15.04 and I also ran `./rebase` today
Do you have any idea how I can fix this?
I did not change the unbundle glob, should I?

**Comment by sunaku** [comment]
Hmm :disappointed_relieved: I wasn't able to reproduce the issue under the `bundle` branch (where I also have NERDcommenter installed) with NeoVim 0.0.0+git201507050731+1732+10~ubuntu15.04.1.

**Comment by awesomefireduck** [comment]
Thanks for helping.  
I'll get back on this when I get home, which will be after the 19th

**Comment by awesomefireduck** [comment]
Well, I backed up all my config and decided to start over.  
I checked out master and now the insert script fails on my first insert :confused::
```
$ ./insert git@github.com:jonstoler/werewolf.vim.git
mkdir: cannot create directory ‘’: No such file or directory
```
It's the same with `$ ./insert jonstoler/werewolf.vim`  
I took a look at the script and tried a path as argument but I end up with this:
```
$ ./insert git@github.com:jonstoler/werewolf.vim.git bundle
./insert: 39: ./insert: cannot create bundle/bundle/werewolf.get: Directory nonexistent
```
Again, the same result with the short version.  

Is the script perhaps broken?

**Comment by sunaku** [comment]
Good catch! :+1: Yes, I made the second argument (where you want to put the bundle) required recently:

```sh
$ ./insert git@github.com:jonstoler/werewolf.vim.git bundle/colorscheme
On branch bundle
Your branch is up-to-date with 'origin/bundle'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   bundle/colorscheme/werewolf.get

bundle/colorscheme/werewolf: Already up-to-date.
```

The insert script previously didn't expect implicit (without a `schema://`) SSH URLs.  This is fixed now. :cake:

Note that you can provide a Github username/reponame directly instead of the SSH/Git/HTTP/S URL:

```sh
$ ./insert jonstoler/werewolf.vim bundle/colorscheme
On branch bundle
Your branch is up-to-date with 'origin/bundle'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   bundle/colorscheme/werewolf.get

bundle/colorscheme/werewolf: Already up-to-date.
```

**Comment by awesomefireduck** [comment]
I can now add the repo correctly (after making the category directory first, see #7 ) but it still doesn't load werewolf. It does in the bundle branch. perhaps something is missing?

**Comment by sunaku** [comment]
Hmm, perhaps before the very first `./update` the Unbundle plugin does not yet exist.  Without it, no bundles will be loaded.  Let me try to repro the bug on a fresh clone with NeoVim myself.

**Comment by sunaku** [comment]
Yes, I believe not having run `./update` initially after cloning this repo was the problem:

```sh
$ bam .vim
‘.vim’ -> ‘.vim.bak’

$ readlink .nvim
.vim

$ git clone https://github.com/sunaku/.vim.git ~/.vim
zsh: correct '~/.vim' to '~/.nvim' [nyae]? n
Cloning into '/home/sunny/.vim'...
remote: Counting objects: 332, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 332 (delta 3), reused 0 (delta 0), pack-reused 322
Receiving objects: 100% (332/332), 49.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (6/6), done.
Checking connectivity... done.

$ cd .vim

$ ./update
bundle/zzz/unbundle: Cloning into '.'...
bundle/zzz/unbundle: Already up-to-date.

$ ./insert jonstoler/werewolf.vim bundle/colour
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   bundle/colour/werewolf.get

bundle/colour/werewolf: Cloning into '.'...
bundle/colour/werewolf: Already up-to-date.

$ nvim
~
~                                                  NVIM 0.0.0-alpha
~
~                                              by Bram Moolenaar et al.
~                                     Vim is open source and freely distributable
~
~                                            Help poor children in Uganda!
~                                   type  :help iccf<Enter>       for information
~
~                                   type  :q<Enter>               to exit
~                                   type  :help<Enter>  or  <F1>  for on-line help
~                                   type  :help nvim<Enter>       for Neovim help
~
~
:Were<TAB>
:Werewolf
WerewolfAuto       WerewolfOff        WerewolfStart      WerewolfTransform
WerewolfEnd        WerewolfOn         WerewolfToggle
:Werewolf<CURSOR>
```

**Comment by sunaku** [comment]
I have created a new `./setup` script that the README now instructs users to run.  It will take care of the initial call to `./update` in addition to the not-so-simple initial git branch creation command. :neckbeard:

**Comment by sunaku** [comment]
Also added a `./help` script to give you usage info on any script provided in this Vim config. :gift:

**Comment by sunaku** [comment]
Closing, as this issue should have been fixed by the `./setup` script. :sweat_smile: Reopen if it's still a problem.
